name: AWS OIDC Auth
description: Configure AWS credentials using OIDC

inputs:
  role-arn:
    required: true
    description: IAM role to assume
  aws-region:
    default: ap-south-1
    description: AWS region

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "${{ inputs.role-arn }}"
        aws-region: "${{ inputs.aws-region }}"
